### ISSUE TITLE
plrtest subscript out of bounds error

### ISSUE THREAD

**Issue by ts2021** [thomashielscher/nonnestcox#1]
I receive the error below

Browse[2]> fineTest0<-plrtest(coxphModelFull,coxphModelRestricted,nested = TRUE)
Error in `[.default`(object1$y, , "time") : subscript out of bounds

coxphModelFull  was created as 

coxphModelFull <- coxph(as.formula(paste(leftFormula, rightFormula, sep = '')), data = data, ties = "efron", weights = weights,
                     robust = TRUE, cluster = combo_id_duration, control = coxph.control(iter.max = 100),x=TRUE)

where 
rightFormula <- paste(covariates, collapse = ' + ')
leftFormula <- paste0('Surv(', START_AGE, ",", END_AGE, ',', STATUS, ') ~ ')

Similarly for coxphModelRestricted

**Comment by thomashielscher** [comment]
The package cannot currently handle start-stop times, i.e. counting process data. But for a comparison of nested Cox models, you can used the standard (partial) likelihood-ratio test from the survival package.
