### ISSUE TITLE
How to interpret final results?

### ISSUE THREAD

**Issue by jgarces02** [thomashielscher/nonnestcox#2]
Hi, 

Thanks for this package, very useful. I understand that variance and likelihood tests are different ones, but I'm a bit confused about the final interpretation when the first one is very significative but none of the models follow H1 in the second test. Is this saying that both model have the same information? How could be that if AIC is different?

```
> data <- source("https://pastebin.com/raw/rGtUSTLz")$value
> m1 <- coxph(Surv(time, event) ~ (var != 0), data = data, x = T)
> m2 <- coxph(Surv(time, event) ~ rcs(var, 3), data = data, x = T)
> plrtest(m1, m2)
Variance test 
  H0: Model 1 and Model 2 are indistinguishable 
  H1: Model 1 and Model 2 are distinguishable 
Fine: p = 0.00147
Non-nested likelihood ratio test 
  H0: Model fits are equally close to true Model 
  H1A: Model 1 fits better than Model 2 
    z = -0.261,   p = 0.603
  H1B: Model 2 fits better than Model 1 
    z = -0.261,   p = 0.3969
  H1: Model fits not equally close to true Model 
    z = -0.261,   two-sided p = 0.7938
> AIC(m1)
[1] 1729.613
> AIC(m2)
[1] 1728.839
```
Thanks in advance.

**Comment by thomashielscher** [comment]
Hi,
the first one is a test on whether models are distinguishable which is a requirement for the second test to be able to indicate that one model is fitting better than the other one. The second test is the one of interest, testing whether one of the models better fits the data. So, for a model to be superior, both tests have to be significant. In your case both models are distinguishable but fit similarly well.

**Comment by jgarces02** [comment]
Ok, thanks for the explanation. I was surprised because the high significance of the first test and not in the second one. I guess is what data has.
